title       = "gaia"
baseURL     = "https://gaia-cli.tamnd.com/"
description = "A command line for gaia."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/gaia-cli"
